# Generated by Django 5.2.4 on 2025-07-16 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_manager_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='portfolio.division'),
        ),
        migrations.AddField(
            model_name='manager',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='portfolio.secteur'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='portfolio.division'),
        ),
    ]
