# Generated by Django 5.2.4 on 2025-07-17 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_user_biography_user_localisation_user_poste'),
    ]

    operations = [
        migrations.CreateModel(
            name='mise_a_jour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_jour', to='portfolio.manager')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mise_a_jour', to='portfolio.projet')),
            ],
        ),
    ]
