# Generated by Django 5.2.4 on 2025-07-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_division_rename_owner_projet_manager_projet_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
