# Generated by Django 5.2.4 on 2025-07-16 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_manager_division_manager_secteur_supervisor_division'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='risk',
        ),
    ]
