# Generated by Django 5.2.4 on 2025-07-17 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_mise_a_jour'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mise_a_jour',
            new_name='miseAjour',
        ),
    ]
