# Generated by Django 5.2.4 on 2025-07-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
