# Generated by Django 5.2.4 on 2025-07-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_projet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='division',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='secteur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
