# Generated by Django 5.2.4 on 2025-07-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_projet_division_alter_projet_secteur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='start_date',
            new_name='date_debut',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='end_date',
            new_name='date_fin',
        ),
    ]
