# Generated by Django 5.2.4 on 2025-07-22 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_rename_start_date_projet_date_debut_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='date_fin',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='projet',
            old_name='date_debut',
            new_name='start_date',
        ),
    ]
