# Generated by Django 5.2.4 on 2025-07-22 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_rename_date_fin_projet_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.supervisor'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.division'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.manager'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='secteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.secteur'),
        ),
    ]
