# Generated by Django 5.2.4 on 2025-07-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_projet_supervisor_alter_projet_division_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='progress',
        ),
        migrations.AlterField(
            model_name='projet',
            name='budget_used',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.CharField(default='nouveau', max_length=50),
        ),
    ]
