# Generated by Django 5.2.4 on 2025-07-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_remove_projet_progress_alter_projet_budget_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.CharField(default='Planifié', max_length=50),
        ),
    ]
