# Generated by Django 5.2.4 on 2025-07-30 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_projet_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rapport',
            old_name='content',
            new_name='periode',
        ),
        migrations.RenameField(
            model_name='rapport',
            old_name='author',
            new_name='requested_by',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='project',
        ),
    ]
