# Generated by Django 5.2.4 on 2025-07-30 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_rename_content_rapport_periode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='assigned_to',
        ),
    ]
