# Generated by Django 5.2.4 on 2025-07-30 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_remove_ressource_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources', to='portfolio.projet'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('materielles ', 'materielles '), ('logicielles ', 'logicielles '), ('informationnelles ', 'informationnelles ')], default='', max_length=100),
        ),
    ]
