# Generated by Django 5.2.4 on 2025-07-31 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_ressource_project_alter_ressource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ressource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ressource',
            name='project',
        ),
        migrations.AddField(
            model_name='ressource',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RessourceUtilisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources_utilisees', to='portfolio.projet')),
                ('ressource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ressources_utilisees', to='portfolio.ressource')),
            ],
        ),
    ]
