# Generated by Django 5.2.4 on 2025-07-31 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_ressource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressource',
            name='type',
            field=models.CharField(choices=[('materielles', 'materielles'), ('logicielles', 'logicielles'), ('informationnelles', 'informationnelles')], default='', max_length=100),
        ),
    ]
